kind: pipeline
type: docker
name: Testing Python CI/CD


steps:
- name: Install and deploy
  image: python

  commands:
  - pip3 curl http://192.168.0.4:5000/run_script

trigger:
  branch:
    exclude:
    - main
    - master
